version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  api:
    depends_on:
      - mysqldb
    build:
      context: ./api
      target: production
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:80
    environment:
      - NODE_ENV=$NODE_ENV
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  client:
    depends_on:
      - api
    image: registry.digitalocean.com/teo-time-registry/nodetypescript_client
    restart: unless-stopped
    environment:
      - NODE_ENV=$NODE_ENV
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
volumes:
  db:
  client:

networks:
  backend:
  frontend:
