GET http://0.0.0.0:5000/?otp=39a3c48a-4d1a-46bc-a1f3-633d7fde366a

###

POST http://0.0.0.0:5000/signup
Content-Type: application/json

{
    "email": "galliziafilippo@gmail.com"
}

###

POST http://0.0.0.0:5000/createbooking
Content-Type: application/json

{
     "start": "2021-10-05T11:30:00.000",
     "end": "2021-10-05T13:00:00.000"
}

###
POST http://0.0.0.0:5000/retrieveAvailability
Content-Type: application/json

{
     "start": "2021-10-05T07:00:00.000",
     "end": "2021-10-05T23:00:00.000"
}


###
GET http://0.0.0.0:5000/login
